name: test

on:
  pull_request:
    paths:
      - 'build/**'
      - '!build/history/**'
      - 'web/**'
      - 'Makefile'
      - '.github/workflows/test.yaml'
  push:
    branches:
      - 'main'
    paths:
      - 'build/**'
      - '!build/history/**'
      - 'web/**'
      - 'Makefile'
      - '.github/workflows/test.yaml'

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  build-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Install dependencies
        run: make deps
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Lint and test
        run: make web-build
