name: update-catalog

on:
  workflow_dispatch:
    inputs:
      force:
        description: Rebuild all sources even when versions are unchanged
        type: boolean
        default: false
  schedule:
    - cron: "0 6 * * *" # every day at 6 AM (UTC)

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - name: Setup flux-schema
        uses: fluxcd/flux-schema/actions/setup@311d886d4669269c92dd9ab5f285051a991ec6c6 # v0.7.0
      - name: Setup flux-operator
        uses: controlplaneio-fluxcd/flux-operator/actions/setup@be9fe84303cf7b8337b74aad1f7e1ccdafa17274 # v0.53.0
      - name: Update catalog
        id: build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FORCE_BUILD: ${{ inputs.force == true && '1' || '' }}
          BUILD_SUMMARY: ${{ runner.temp }}/pr-body.md
          RUN_TO_COMPLETION: "1"
        run: make build
      - name: Checkout example repository
        if: steps.build.outputs.changed == 'true'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: fluxcd/flux2-kustomize-helm-example
          path: example
      - name: Configure smoke test
        if: steps.build.outputs.changed == 'true'
        run: |
          cat > .fluxschema-smoke.yml <<EOF
          apiVersion: schema.plugin.fluxcd.io/v1beta1
          kind: Config
          validate:
            schemaLocation:
              - ${GITHUB_WORKSPACE}/catalog
          EOF
      - name: Test validate action
        if: steps.build.outputs.changed == 'true'
        uses: fluxcd/flux-schema/actions/validate@311d886d4669269c92dd9ab5f285051a991ec6c6 # v0.7.0
        with:
          path: example
          config: .fluxschema-smoke.yml
      - name: Create Pull Request
        if: steps.build.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: update-catalog
          title: "Update catalog"
          commit-message: "Update catalog"
          committer: GitHub <noreply@github.com>
          signoff: true
          body-path: ${{ runner.temp }}/pr-body.md
          add-paths: |
            catalog
            build/history
            README.md
